name: Flutter Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2' # Change if needed

      - name: Install Dependencies
        run: |
          cd example
          flutter pub get

      - name: Build APK
        run: |
          cd example
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: betterplayer-apk
          path: example/build/app/outputs/flutter-apk/app-release.apk
